sudo: required
services:
  - docker
install: docker build -t eulerian .
jobs:
  include:
    - stage: test
      script: docker run -it eulerian pylama
    -
      script: docker run -it eulerian pytest
